mysite/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

import spirit.urls

# Override admin login for security purposes
from django.contrib.auth.decorators import login_required
admin.site.login = login_required(admin.site.login)


urlpatterns = [
    url(r'^', include(spirit.urls)),

    # This is the default django admin
    # it's not needed to use Spirit
    url(r'^admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spirit/admin/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url

from . import views
import spirit.category.admin.urls
import spirit.comment.flag.admin.urls
import spirit.topic.admin.urls
import spirit.user.admin.urls


app_name = 'admin'
urlpatterns = [
    url(r'^$', views.dashboard, name='index'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^config/$', views.config_basic, name='config-basic'),

    url(r'^category/', include(spirit.category.admin.urls)),
    url(r'^comment/flag/', include(spirit.comment.flag.admin.urls)),
    url(r'^topic/', include(spirit.topic.admin.urls)),
    url(r'^user/', include(spirit.user.admin.urls)),
]

spirit/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url

import spirit.topic.views
import spirit.admin.urls
import spirit.user.urls
import spirit.search.urls
import spirit.category.urls
import spirit.topic.urls
import spirit.comment.urls


app_name = 'spirit'
urlpatterns = [
    url(r'^$', spirit.topic.views.index_active, name='index'),
    url(r'^anymail/', include('anymail.urls')),
    url(r'^st/admin/', include(spirit.admin.urls)),
    url(r'^user/', include(spirit.user.urls)),
    url(r'^search/', include(spirit.search.urls)),
    url(r'^category/', include(spirit.category.urls)),
    url(r'^topic/', include(spirit.topic.urls)),
    url(r'^comment/', include(spirit.comment.urls)),
]

spirit/user/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include

from .auth import urls as auth_urls
from . import views


app_name = 'user'
urlpatterns = [
    url(r'^$', views.update, name='update'),
    url(r'^password-change/$', views.password_change, name='password-change'),
    url(r'^email-change/$', views.email_change, name='email-change'),
    url(r'^email-change/(?P<token>[0-9A-Za-z_\-\.]+)/$',
        views.email_change_confirm,
        name='email-change-confirm'),

    url(r'^(?P<pk>[0-9]+)/$', views.comments, kwargs={'slug': ""}, name='detail'),
    url(r'^(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/$', views.comments, name='detail'),

    url(r'^topics/(?P<pk>[0-9]+)/$', views.topics, kwargs={'slug': ""}, name='topics'),
    url(r'^topics/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/$', views.topics, name='topics'),

    url(r'^likes/(?P<pk>[0-9]+)/$', views.likes, kwargs={'slug': ""}, name='likes'),
    url(r'^likes/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/$', views.likes, name='likes'),

    url(r'^menu/$', views.menu, name='menu'),

    url(r'^', include(auth_urls)),
]

spirit/comment/flag/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone

from ...core.conf import settings

REASON_CHOICES = (
    (0, _("Spam")),
    (1, _("Other")))


class CommentFlag(models.Model):

    moderator = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='st_comment_flags',
        null=True,
        blank=True,
        on_delete=models.CASCADE)
    comment = models.OneToOneField(
        'spirit_comment.Comment',
        on_delete=models.CASCADE)

    date = models.DateTimeField(default=timezone.now)
    is_closed = models.BooleanField(default=False)

    class Meta:
        ordering = ['-date', '-pk']
        verbose_name = _("comment flag")
        verbose_name_plural = _("comments flags")

    # def get_absolute_url(self):
        # pass


class Flag(models.Model):

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='st_flags',
        on_delete=models.CASCADE)
    comment = models.ForeignKey(
        'spirit_comment.Comment',
        on_delete=models.CASCADE)

    date = models.DateTimeField(default=timezone.now)
    reason = models.IntegerField(_("reason"), choices=REASON_CHOICES)
    body = models.TextField(_("body"), blank=True)

    class Meta:
        unique_together = ('user', 'comment')
        ordering = ['-date', '-pk']
        verbose_name = _("flag")
        verbose_name_plural = _("flags")

spirit/admin/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.utils.translation import ugettext_lazy as _

from djconfig.forms import ConfigForm


class BasicConfigForm(ConfigForm):

    site_name = forms.CharField(initial="Spirit", label=_("site name"))
    site_description = forms.CharField(initial="", label=_("site description"), max_length=75, required=False)
    template_footer = forms.CharField(initial="", label=_("footer snippet"), required=False,
                                      widget=forms.Textarea(attrs={'rows': 2, }),
                                      help_text=_("This gets rendered just before the footer in your template."))
    comments_per_page = forms.IntegerField(initial=20, label=_("comments per page"), min_value=1, max_value=100)
    topics_per_page = forms.IntegerField(initial=20, label=_("topics per page"), min_value=1, max_value=100)

spirit/category/admin/forms.py
# -*- coding: utf-8 -*-

import re

from django import forms
from django.db.models import Max
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import smart_text
from django.utils import timezone

from ..models import Category


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = (
            "parent",
            "title",
            "description",
            "is_global",
            "is_closed",
            "is_removed",
            "color")

    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        queryset = Category.objects.visible().parents()

        if self.instance.pk:
            queryset = queryset.exclude(pk=self.instance.pk)

        self.fields['parent'] = forms.ModelChoiceField(
            queryset=queryset, required=False)
        self.fields['parent'].label_from_instance = (
            lambda obj: smart_text(obj.title))

    def clean_parent(self):
        parent = self.cleaned_data["parent"]

        if self.instance.pk:
            has_children = self.instance.category_set.all().exists()

            if parent and has_children:
                raise forms.ValidationError(
                    _("The category you are updating "
                      "can not have a parent since it has childrens"))

        return parent

    def clean_color(self):
        color = self.cleaned_data["color"]

        if color and not re.match(r'^#([A-Fa-f0-9]{3}){1,2}$', color):
            raise forms.ValidationError(
                _("The input is not a valid hex color."))

        return color

    def get_max_sort(self):
        return Category.objects.aggregate(max_sort=Max('sort'))['max_sort'] or 0

    def save(self, commit=True):
        if not self.instance.pk:
            self.instance.sort = self.get_max_sort() + 1
        self.instance.reindex_at = timezone.now()
        return super(CategoryForm, self).save(commit)

spirit/comment/bookmark/forms.py
# -*- coding: utf-8 -*-

from django import forms

from .models import CommentBookmark


class BookmarkForm(forms.ModelForm):

    class Meta:
        model = CommentBookmark
        fields = ['comment_number']

    def __init__(self, user=None, topic=None, *args, **kwargs):
        super(BookmarkForm, self).__init__(*args, **kwargs)
        self.user = user
        self.topic = topic

    def save(self, commit=True):
        # Bookmark is created/updated on topic view.
        CommentBookmark.increase_to(
            user=self.user,
            topic=self.topic,
            comment_number=self.cleaned_data['comment_number'])

spirit/comment/flag/admin/forms.py
# -*- coding: utf-8 -*-

from django import forms

from ..models import CommentFlag


class CommentFlagForm(forms.ModelForm):

    class Meta:
        model = CommentFlag
        fields = ("is_closed", )

    def __init__(self, user=None, *args, **kwargs):
        super(CommentFlagForm, self).__init__(*args, **kwargs)
        self.user = user

    def save(self, commit=True):
        self.instance.moderator = self.user
        return super(CommentFlagForm, self).save(commit)

spirit/comment/flag/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.utils.translation import ugettext_lazy as _
from django.db import IntegrityError, transaction
from django.utils import timezone

from .models import Flag, CommentFlag


class FlagForm(forms.ModelForm):

    class Meta:
        model = Flag
        fields = ['reason', 'body']

    def __init__(self, user=None, comment=None, *args, **kwargs):
        super(FlagForm, self).__init__(*args, **kwargs)
        self.user = user
        self.comment = comment

    def clean(self):
        cleaned_data = super(FlagForm, self).clean()

        flag = Flag.objects.filter(user=self.user,
                                   comment=self.comment)

        if flag.exists():
            # Do this since some of the unique_together fields are excluded.
            raise forms.ValidationError(_("This flag already exists"))

        return cleaned_data

    def save(self, commit=True):
        if not self.instance.pk:
            self.instance.user = self.user
            self.instance.comment = self.comment

            try:
                with transaction.atomic():
                    CommentFlag.objects.update_or_create(
                        comment=self.comment,
                        defaults={'date': timezone.now(), })
            except IntegrityError:
                pass

        return super(FlagForm, self).save(commit)

spirit/comment/forms.py
# -*- coding: utf-8 -*-

import os
import logging

from django import forms
from django.core.files.storage import default_storage
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import smart_bytes
from django.core.files.uploadedfile import TemporaryUploadedFile

from ..core.conf import settings
from ..core import utils
from ..core.utils.markdown import Markdown
from ..topic.models import Topic
from .poll.models import CommentPoll, CommentPollChoice
from .models import Comment

logger = logging.getLogger(__name__)

# Mostly for Windows users who don't need file upload
try:
    import magic
except ImportError as err:
    # There used to be a logger.exception here but
    # the traceback made things confusing when an unhandled was raised
    if settings.ST_UPLOAD_FILE_ENABLED:
        logger.info(
            'File upload requires running: '
            '`pip install django-spirit[files]`')
        raise err
    magic = None


def save_user_file(user, file, subdir, hashed=False):
    """
    Save user media file into sub-dir. \
    The `hashed`` param prevents file duplication
    """
    file_path = utils.generate_filename(file, hashed=hashed)
    name = os.path.join('spirit', subdir, str(user.pk), file_path)
    name = default_storage.save(name, file)
    file.name = os.path.basename(file_path)
    file.url = default_storage.url(name)
    return file


class CommentForm(forms.ModelForm):
    comment = forms.CharField(
        label=_('Comment'),
        max_length=settings.ST_COMMENT_MAX_LEN,
        widget=forms.Textarea)
    comment_hash = forms.CharField(
        max_length=32,
        widget=forms.HiddenInput,
        required=False)

    class Meta:
        model = Comment
        fields = ['comment', 'anonymous']

    def __init__(self, user=None, topic=None, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.user = user
        self.topic = topic
        self.mentions = None  # {username: User, }
        self.polls = None  # {polls: [], choices: []}
        self.fields['comment'].widget.attrs['placeholder'] = _("Write comment...")
        self.fields['anonymous'] = forms.BooleanField(label='Post as Anonymous', required=False, help_text='Post as Anonymous')

    def get_comment_hash(self):
        assert self.topic

        # This gets saved into
        # User.last_post_hash,
        # it does not matter whether
        # is a safe string or not
        comment_hash = self.cleaned_data.get('comment_hash', None)

        if comment_hash:
            return comment_hash

        return utils.get_hash((
            smart_bytes(self.cleaned_data['comment']),
            smart_bytes('thread-{}'.format(self.topic.pk)),
            smart_bytes(self.cleaned_data['anonymous'])
        ))

    def _get_comment_html(self):
        user = self.user or self.instance.user
        markdown = Markdown(no_follow=not user.st.is_moderator)
        comment_html = markdown.render(self.cleaned_data['comment'])
        self.mentions = markdown.get_mentions()
        self.polls = markdown.get_polls()
        return comment_html

    def _save_polls(self):
        assert self.instance.pk
        assert self.polls is not None

        polls = self.polls['polls']
        choices = self.polls['choices']

        CommentPoll.update_or_create_many(comment=self.instance, polls_raw=polls)
        CommentPollChoice.update_or_create_many(comment=self.instance, choices_raw=choices)

    def save(self, commit=True):
        if not self.instance.pk:
            self.instance.user = self.user
            self.instance.topic = self.topic

        self.instance.comment_html = self._get_comment_html()
        comment = super(CommentForm, self).save(commit)

        if commit:
            self._save_polls()

        return comment


class CommentMoveForm(forms.Form):

    topic = forms.ModelChoiceField(queryset=Topic.objects.all(), widget=forms.TextInput)

    def __init__(self, topic, *args, **kwargs):
        super(CommentMoveForm, self).__init__(*args, **kwargs)
        self.fields['comments'] = forms.ModelMultipleChoiceField(
            queryset=Comment.objects.filter(topic=topic),
            widget=forms.CheckboxSelectMultiple
        )

    def save(self):
        comments = self.cleaned_data['comments']
        comments_list = list(comments)
        topic = self.cleaned_data['topic']
        comments.update(topic=topic)

        # Update topic in comment instance
        for c in comments_list:
            c.topic = topic

        return comments_list


class CommentImageForm(forms.Form):

    image = forms.ImageField(max_length=255)

    def __init__(self, user=None, *args, **kwargs):
        super(CommentImageForm, self).__init__(*args, **kwargs)
        self.user = user

    def clean_image(self):
        file = self.cleaned_data['image']
        ext = os.path.splitext(file.name)[1].lstrip('.').lower()

        if (ext not in settings.ST_ALLOWED_UPLOAD_IMAGE_FORMAT or
                file.image.format.lower() not in settings.ST_ALLOWED_UPLOAD_IMAGE_FORMAT):
            raise forms.ValidationError(
                _("Unsupported file format. Supported formats are %s.") %
                  ", ".join(settings.ST_ALLOWED_UPLOAD_IMAGE_FORMAT))

        return file

    def save(self):
        return save_user_file(
            user=self.user,
            file=self.cleaned_data['image'],
            subdir='images',
            hashed=settings.ST_PREVENT_SOME_FILE_DUPLICATION)


class CommentFileForm(forms.Form):

    file = forms.FileField(max_length=255)

    def __init__(self, user=None, *args, **kwargs):
        super(CommentFileForm, self).__init__(*args, **kwargs)
        self.user = user

    def clean_file(self):
        file = self.cleaned_data['file']

        if not magic:
           raise forms.ValidationError(_("The file could not be validated"))

        # Won't ever raise. Has at most one '.' so lstrip is fine here
        ext = os.path.splitext(file.name)[1].lstrip('.').lower()
        if ext not in settings.ST_ALLOWED_UPLOAD_FILE_MEDIA_TYPE:
            raise forms.ValidationError(
                _("Unsupported file extension %(extension)s. "
                  "Supported extensions are %(supported)s.") % {
                    'extension': ext,
                    'supported': ", ".join(
                        sorted(settings.ST_ALLOWED_UPLOAD_FILE_MEDIA_TYPE.keys()))})

        try:
            if isinstance(file, TemporaryUploadedFile):
                file_mime = magic.from_file(file.temporary_file_path(), mime=True)
            else:  # In-memory file
                file_mime = magic.from_buffer(file.read(), mime=True)
        except magic.MagicException as e:
            logger.exception(e)
            raise forms.ValidationError(_("The file could not be validated"))

        mime = settings.ST_ALLOWED_UPLOAD_FILE_MEDIA_TYPE.get(ext, None)
        if mime != file_mime:
            raise forms.ValidationError(
                _("Unsupported file mime type %(mime)s. "
                  "Supported types are %(supported)s.") % {
                    'mime': file_mime,
                    'supported': ", ".join(
                        sorted(settings.ST_ALLOWED_UPLOAD_FILE_MEDIA_TYPE.values()))})

        return file

    def save(self):
        return save_user_file(
            user=self.user,
            file=self.cleaned_data['file'],
            subdir='files',
            hashed=settings.ST_PREVENT_SOME_FILE_DUPLICATION)

spirit/core/templates/spirit/_base.html
{% load spirit_tags i18n %}
{% load static %}
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <title>{% block title %}{% endblock %} - {{ config.site_name }}</title>
  <meta name="description" content="{{ config.site_description }}">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="{% static "spirit/stylesheets/styles.all.min.css" %}">
  <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">-->

  <!--<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>-->
  <script src="{% static "spirit/scripts/all.min.js" %}"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

  <script>
    document.addEventListener('DOMContentLoaded', function() {
      stModules.tab(document.querySelectorAll('.js-tab'));
      stModules.postify(document.querySelectorAll('.js-post'), {
        csrfToken: "{{ csrf_token }}"
      });
      stModules.messages(document.querySelectorAll('.js-messages'));
      {% if user.is_authenticated %}
        stModules.notification(document.querySelectorAll('.js-tab-notification'), {
          notificationUrl: "{% url "spirit:topic:notification:index-ajax" %}",
          notificationListUrl: "{% url "spirit:topic:notification:index-unread" %}",
          mentionTxt: "{% trans "{user} has mention you on {topic}" %}",
          topicNoTxt: "{{user}} has created a topic {{topic}}",
          commentTxt: "{% trans "{user} has commented on {topic}" %}",
          showAll: "{% trans "Show all" %}",
          empty: "{% trans "No new notifications, yet" %}",
          unread: "{% trans "unread" %}"
        });
      {% endif %}
    });
  </script>

  {% block head-extra %}{% endblock %}

  <!--[if (lt IE 9) & (!IEMobile)]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/selectivizr/1.0.2/selectivizr-min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6/html5shiv.min.js"></script>
    <![endif]-->

  <style>
    .container {
      max-width: 1080px;
    }
  </style>

</head>

<body>
<div class="row">
<div class="container flex-row justify-content-between">
{% include 'spirit/_header.html' %}
{% render_messages messages %}
{% block content %}{% endblock %}
{% include 'spirit/_footer.html' %}
  </div>
</div>

</body>

</html>

spirit/core/templates/spirit/_footer.html
{% load spirit_tags %}
{% load_settings 'ST_MATH_JAX' %}

{{ config.template_footer|safe }}

{% spaceless %}
  <footer class="footer">
    <div class="footer-container">
      <a class="footer-logo" href="http://www.spirit-project.com">Spirit</a>
    </div>
  </footer>
{% endspaceless %}

{% if st_settings.ST_MATH_JAX %}
  <script type="text/x-mathjax-config">
    (function () {
      var elms = document.querySelectorAll(".math");
      MathJax.Hub.Config({
        elements: elms,
        skipStartupTypeset: elms.length === 0
      });
    })();
  </script>
  <script type="text/javascript" async
    src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML">
  </script>
{% endif %}

spirit/core/templates/spirit/_form.html
{% if next %}<input type="hidden" name="next" value="{{ next }}" />{% endif %}

{{ form.non_field_errors }}

{% for field in form.hidden_fields %}
  {{ field.errors }}
  {{ field }}
{% endfor %}

{% for field in form.visible_fields %}
  <div class="field">
    {{ field.label_tag }}
    {{ field.errors }}
    {{ field }}
    {{ field.help_text }}
  </div>
{% endfor %}

spirit/core/templates/spirit/_formset.html
{{ formset.management_form }}
{{ formset.non_form_errors }}

{% for f in formset %}
  {% include "spirit/_form.html" with form=f %}
{% endfor %}

spirit/core/templates/spirit/_header.html
{% load spirit_tags i18n %}

<header class="header js-tabs-container">
  <a class="header-logo" href="{% url "spirit:index" %}">{{ config.site_name }}</a>

  {% if user.is_authenticated %}
    {% has_topic_notifications user as has_notifications %}

    {% spaceless %}
      <ul class="header-tabs">
        <li>
          <!-- <a class="header-tab-link js-tab"
            href="{% url "spirit:search:search" %}"
            data-related=".js-search-content">
            <i class="fa fa-search"></i>
          </a> -->
        </li>
        <li>
          <!-- <a class="header-tab-link js-tab-notification{% if has_notifications %} is-highlighted{% endif %}"
            href="{% url "spirit:topic:notification:index" %}"
            data-related=".js-notifications-content">
            <i class="fa fa-bell"></i>
          </a> -->
          <a href="{% url "spirit:topic:notification:index-unread" %}" style="color: red;">notification({{ notification_count }})</a>
        </li>
        <li>
          <a class="header-tab-link js-tab"
            href="{% url "spirit:user:menu" %}"
            data-related=".js-user-content"
          >{{ user.st.nickname }} <i class="fa fa-chevron-down"></i></a>
        </li>
      </ul>
    {% endspaceless %}

    <div class="header-tabs-content">

      <div class="header-tab-content js-tab-content js-user-content">
        <nav class="header-nav">
          {% spaceless %}
            <ul class="menu">
              {% if profile.is_allowed == True %}
                <li>
                  <a class="menu-link" href="{% url "spirit:user:detail" pk=user.pk slug=user.st.slug %}"
                  >{% trans "Profile" %}</a>
                </li>
                <li>
                  <a class="menu-link" href="{% url "spirit:topic:index-active" %}">{% trans "Topics" %}</a>
                </li>
                <li>
                  <a class="menu-link" href="{% url "spirit:topic:unread:index" %}">{% trans "Unread topics" %}</a>
                </li>
                <li>
                  <a class="menu-link" href="{% url "spirit:topic:private:index" %}">{% trans "Private topics" %}</a>
                </li>



                  {% if user.st.is_administrator %}
                    <li>
                      <a class="menu-link" href="{% url "spirit:admin:config-basic" %}" id="change_password">{% trans "Password" %}</a>
                    </li>
                  {% endif %}
              {% endif %}
              <li>
                <a class="menu-link js-post"
                  href="{% url "spirit:user:auth:logout" %}"
                >{% trans "Log out" %}</a>
              </li>
            </ul>
          {% endspaceless %}
        </nav>
      </div>

      <div class="header-tab-content js-tab-content js-notifications-content"></div>

      <div class="header-tab-content js-tab-content js-search-content">
        {% render_search_form %}
      </div>

    </div>
  {% else %}
    <a class="header-link"
      href="{% url "spirit:user:auth:login" %}?next={% firstof request.get_full_path|urlencode '/' %}"
    >{% trans "Log in" %}</a>
  {% endif %}
</header>